### ISSUE TITLE
Model#_getValueSync is defined twice

### ISSUE THREAD

**Issue by lingz** [Netflix/falcor#793]
It's defined here:

https://github.com/Netflix/falcor/blob/a201bbde431a2b7319b671b34b05087dff1d479a/lib/Model.js#L336

and again here:

https://github.com/Netflix/falcor/blob/a201bbde431a2b7319b671b34b05087dff1d479a/lib/Model.js#L606

Looks like there is a redundant definition? Can one of them be safely deleted?

**Comment by roastlechon** [comment]
Looking at the lines, they do not look to be redundant definitions, but assigned different functions.

I did my due diligence of pulling the code and deleting L606: `Model.prototype._getValueSync = require("./get/getValueSync");` and ran `gulp test` and got 3 failing tests.

```
  1) Falcor Model Operations Get getVersionSync should get a version:
     Error: Model#getValueSync must be called with an Array path.
      at Model.getValueSync [as _getValueSync] (/Users/roastlechon/projects/falcor/lib/get/sync.js:6:15)
      at Model._getVersion (/Users/roastlechon/projects/falcor/lib/get/getVersion.js:3:21)
      at Model.getVersion (/Users/roastlechon/projects/falcor/lib/Model.js:416:17)
      at Context.<anonymous> (/Users/roastlechon/projects/falcor/test/falcor/get/get.gen.spec.js:9:29)
      at callFn (/Users/roastlechon/projects/falcor/node_modules/mocha/lib/runnable.js:250:21)
      at Test.Runnable.run (/Users/roastlechon/projects/falcor/node_modules/mocha/lib/runnable.js:243:7)
      at Runner.runTest (/Users/roastlechon/projects/falcor/node_modules/mocha/lib/runner.js:373:10)
      at /Users/roastlechon/projects/falcor/node_modules/mocha/lib/runner.js:451:12
      at next (/Users/roastlechon/projects/falcor/node_modules/mocha/lib/runner.js:298:14)
      at /Users/roastlechon/projects/falcor/node_modules/mocha/lib/runner.js:308:7

  2) Falcor Model Operations Get getVersionSync should get a version on the root model:
     Error: Model#getValueSync must be called with an Array path.
      at Model.getValueSync [as _getValueSync] (/Users/roastlechon/projects/falcor/lib/get/sync.js:6:15)
      at Model._getVersion (/Users/roastlechon/projects/falcor/lib/get/getVersion.js:3:21)
      at Model.getVersion (/Users/roastlechon/projects/falcor/lib/Model.js:416:17)
      at Context.<anonymous> (/Users/roastlechon/projects/falcor/test/falcor/get/get.gen.spec.js:14:29)
      at callFn (/Users/roastlechon/projects/falcor/node_modules/mocha/lib/runnable.js:250:21)
      at Test.Runnable.run (/Users/roastlechon/projects/falcor/node_modules/mocha/lib/runnable.js:243:7)
      at Runner.runTest (/Users/roastlechon/projects/falcor/node_modules/mocha/lib/runner.js:373:10)
      at /Users/roastlechon/projects/falcor/node_modules/mocha/lib/runner.js:451:12
      at next (/Users/roastlechon/projects/falcor/node_modules/mocha/lib/runner.js:298:14)
      at /Users/roastlechon/projects/falcor/node_modules/mocha/lib/runner.js:308:7

  3) Falcor Model Operations Get getVersionSync should get -1 if no path exists.:
     Error: Model#getValueSync must be called with an Array path.
      at Model.getValueSync [as _getValueSync] (/Users/roastlechon/projects/falcor/lib/get/sync.js:6:15)
      at Model._getVersion (/Users/roastlechon/projects/falcor/lib/get/getVersion.js:3:21)
      at Model.getVersion (/Users/roastlechon/projects/falcor/lib/Model.js:416:17)
      at Context.<anonymous> (/Users/roastlechon/projects/falcor/test/falcor/get/get.gen.spec.js:20:29)
      at callFn (/Users/roastlechon/projects/falcor/node_modules/mocha/lib/runnable.js:250:21)
      at Test.Runnable.run (/Users/roastlechon/projects/falcor/node_modules/mocha/lib/runnable.js:243:7)
      at Runner.runTest (/Users/roastlechon/projects/falcor/node_modules/mocha/lib/runner.js:373:10)
      at /Users/roastlechon/projects/falcor/node_modules/mocha/lib/runner.js:451:12
      at next (/Users/roastlechon/projects/falcor/node_modules/mocha/lib/runner.js:298:14)
      at /Users/roastlechon/projects/falcor/node_modules/mocha/lib/runner.js:308:7
```

**Comment by lingz** [comment]
I deleted line 336 and ran the test and it passed with no errors. @roastlechon

**Comment by roastlechon** [comment]
So assuming L606 is what they intended to assign to _getValueSync and L336 is just overridden by L606 it's probably safe to delete!

amiright?!

**Comment by trxcllnt** [comment]
From what I remember, getValueSync used to be public API, and the first entry was without the underscore. At some point the API was deprecated and made "private," but it seems like the private implementation method wasn't renamed.

**Comment by lingz** [comment]
Does this mean the former assignment and the file it imports could both be deleted?

**Comment by trxcllnt** [comment]
@lingz I think the fix here is to change [this entry on the Model prototype](https://github.com/Netflix/falcor/blob/a201bbde431a2b7319b671b34b05087dff1d479a/lib/Model.js#L606) should be renamed to `__getValueSync`, and [this call in `lib/get/sync.js`](https://github.com/Netflix/falcor/blob/a201bbde431a2b7319b671b34b05087dff1d479a/lib/get/sync.js#L12) should be changed to call `this.__getValueSync`.

**Comment by jcranendonk** [comment]
The duplicate assignment was removed in the 2.0 release.
